/**
 * pdfService.js
 * Generates a beautifully designed multi-page Matrix of Destiny PDF report.
 * Uses jsPDF for layout + html2canvas to capture the SVG chart.
 */

import jsPDF from 'jspdf';
import { ARCHETYPES, getLuckyNumbers, getFavorableColors, getCareerPaths,
  getMantra, getShadowWork, getRelationshipProfile, getHealthInsights } from '../utils/predictionEngine';

// ─── DESIGN TOKENS ────────────────────────────────────────────────────────────
const C = {
  bg:         [3,   7,  18],    // #030712
  surface:    [7,  15,  29],    // #070f1d
  surface2:   [11, 22,  42],    // #0b162a
  gold:       [201,151,  0],    // #c99700
  goldLight:  [245,200, 66],    // #f5c842
  white:      [240,240,245],    // #f0f0f5
  silver:     [180,180,195],    // silver
  muted:      [100,110,130],    // muted text
  accent1:    [ 96,192,128],    // green  — wealth
  accent2:    [224,128,160],    // pink   — love
  accent3:    [160,128,208],    // purple — karmic
  accent4:    [ 96,144,224],    // blue   — purpose
  accent5:    [224,144, 80],    // orange — forecast
};

const W = 210; // A4 width mm
const H = 297; // A4 height mm
const ML = 18; // margin left
const MR = 18; // margin right
const CW = W - ML - MR; // content width

// ─── HELPERS ─────────────────────────────────────────────────────────────────

const rgb  = (doc, arr) => doc.setTextColor(...arr);
const fill = (doc, arr) => doc.setFillColor(...arr);
const stroke = (doc, arr) => doc.setDrawColor(...arr);

const rect = (doc, x, y, w, h, r = 3) => {
  doc.roundedRect(x, y, w, h, r, r, 'F');
};

const line = (doc, x1, y1, x2, y2) => {
  doc.line(x1, y1, x2, y2);
};

// Wrap text into lines of maxWidth
const wrapText = (doc, text, maxWidth) => {
  if (!text) return [];
  return doc.splitTextToSize(String(text), maxWidth);
};

// Draw text with auto line height, returns new Y
const drawWrapped = (doc, text, x, y, maxWidth, lineH = 5) => {
  const lines = wrapText(doc, text, maxWidth);
  lines.forEach((l, i) => doc.text(l, x, y + i * lineH));
  return y + lines.length * lineH;
};

// Page background
const pageBg = (doc) => {
  fill(doc, C.bg);
  rect(doc, 0, 0, W, H, 0);
  // subtle top gradient simulation — a slightly lighter rect at top
  doc.setFillColor(10, 18, 35);
  doc.rect(0, 0, W, 60, 'F');
};

// Daiwaya header bar
const headerBar = (doc, pageNum, totalPages) => {
  // Top gold line
  stroke(doc, C.gold);
  doc.setLineWidth(0.4);
  line(doc, 0, 8, W, 8);

  // Brand
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  rgb(doc, C.goldLight);
  doc.text('DAIWAYA.LK', ML, 5.5);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  rgb(doc, C.muted);
  doc.text('Matrix of Destiny · Sri Lanka', ML + 28, 5.5);

  // Page number
  doc.setFontSize(7);
  rgb(doc, C.muted);
  doc.text(`${pageNum} / ${totalPages}`, W - MR, 5.5, { align: 'right' });
};

// Footer bar
const footerBar = (doc) => {
  stroke(doc, [30, 40, 60]);
  doc.setLineWidth(0.3);
  line(doc, ML, H - 10, W - MR, H - 10);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.5);
  rgb(doc, C.muted);
  doc.text('Generated by Daiwaya.lk — Your cosmic blueprint, revealed.', W / 2, H - 6, { align: 'center' });
};

// Section heading with gold accent bar
const sectionHead = (doc, title, y, iconColor = C.gold) => {
  fill(doc, iconColor);
  rect(doc, ML, y, 3, 5, 1);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  rgb(doc, C.white);
  doc.text(title, ML + 6, y + 4);
  return y + 10;
};

// Node badge — small gold circle with number
const nodeBadge = (doc, n, x, y, r = 5) => {
  fill(doc, C.surface2);
  doc.circle(x, y, r, 'F');
  stroke(doc, C.gold);
  doc.setLineWidth(0.4);
  doc.circle(x, y, r, 'S');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(r > 5 ? 9 : 7);
  rgb(doc, C.goldLight);
  doc.text(String(n), x, y + (r > 5 ? 3 : 2.2), { align: 'center' });
};

// Stat card
const statCard = (doc, x, y, w, h, label, value, sub, accent = false) => {
  fill(doc, accent ? [40, 30, 5] : C.surface);
  rect(doc, x, y, w, h);
  if (accent) {
    stroke(doc, C.gold);
    doc.setLineWidth(0.3);
    doc.roundedRect(x, y, w, h, 3, 3, 'S');
  }
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6);
  rgb(doc, accent ? C.gold : C.muted);
  doc.text(label.toUpperCase(), x + w / 2, y + 4, { align: 'center' });
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  rgb(doc, accent ? C.goldLight : C.white);
  doc.text(String(value), x + w / 2, y + 11, { align: 'center' });
  if (sub) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(5.5);
    rgb(doc, C.muted);
    const subLines = wrapText(doc, sub, w - 4);
    subLines.slice(0, 2).forEach((l, i) => doc.text(l, x + w / 2, y + 14.5 + i * 3.5, { align: 'center' }));
  }
};

// Reading section block
const readingBlock = (doc, title, content, y, accentColor = C.gold, maxY = H - 20) => {
  if (!content || y > maxY - 20) return y;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  rgb(doc, accentColor);
  doc.text(title, ML, y);
  y += 5;

  // Divider
  stroke(doc, accentColor);
  doc.setLineWidth(0.2);
  line(doc, ML, y, W - MR, y);
  y += 4;

  // Body — split into paragraphs
  const paras = (content || '').split('\n\n').filter(Boolean).map(p =>
    p.replace(/^#+\s*/gm, '').replace(/\*\*/g, '').trim()
  );

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  rgb(doc, C.silver);

  for (const para of paras) {
    const lines = wrapText(doc, para, CW);
    const blockH = lines.length * 4.5;
    if (y + blockH > maxY) break;
    lines.forEach((l, i) => doc.text(l, ML, y + i * 4.5));
    y += blockH + 3;
  }

  return y + 4;
};

// Draw the octagram SVG as a canvas snapshot — fallback to vector drawing
const drawOctagramVector = (doc, cx, cy, r, chart) => {
  const pt = (i, radius = r) => {
    const angle = (i * 45 - 90) * Math.PI / 180;
    return { x: cx + radius * Math.cos(angle), y: cy + radius * Math.sin(angle) };
  };

  // Two squares (octagram)
  const sq1 = [0,2,4,6].map(i => pt(i));
  const sq2 = [1,3,5,7].map(i => pt(i));

  const drawPoly = (pts, fillColor, strokeColor, lw) => {
    fill(doc, fillColor);
    stroke(doc, strokeColor);
    doc.setLineWidth(lw);
    doc.lines(
      pts.slice(1).map((p, i) => [p.x - pts[i].x, p.y - pts[i].y]),
      pts[0].x, pts[0].y, [1,1], 'FD', true
    );
  };

  // Background circle
  fill(doc, C.surface2);
  stroke(doc, [30,45,70]);
  doc.setLineWidth(0.3);
  doc.circle(cx, cy, r + 8, 'FD');

  // Guide circles
  stroke(doc, [40, 55, 80]);
  doc.setLineWidth(0.2);
  doc.circle(cx, cy, r, 'S');
  doc.circle(cx, cy, r * 0.69, 'S');
  doc.circle(cx, cy, r * 0.41, 'S');

  // Octagram squares
  drawPoly(sq1, [50,38,5], C.gold, 0.5);
  drawPoly(sq2, [20,30,55], [80,110,180], 0.4);

  // Channel lines to center
  stroke(doc, C.gold);
  doc.setLineWidth(0.3);
  [[2],[4],[6],[0]].forEach(([i]) => {
    const p = pt(i);
    doc.line(p.x, p.y, cx, cy);
  });

  // Mid-ring nodes
  const midVals = [
    { i:0, v: chart.moneyChannel?.entrance },
    { i:2, v: chart.lifePath },
    { i:4, v: chart.relationshipChannel?.entrance },
    { i:6, v: chart.root },
  ];
  midVals.forEach(({ i, v }) => nodeBadge(doc, v, pt(i, r*0.69).x, pt(i, r*0.69).y, 3.5));

  // Outer nodes
  const outerVals = [
    { i:0, v: chart.top    }, { i:1, v: chart.skyNode },
    { i:2, v: chart.right  }, { i:3, v: chart.moneyChannel?.heart },
    { i:4, v: chart.bottom }, { i:5, v: chart.karmicTail?.middle },
    { i:6, v: chart.left   }, { i:7, v: chart.earthNode },
  ];
  outerVals.forEach(({ i, v }) => nodeBadge(doc, v, pt(i).x, pt(i).y, 4.5));

  // Center — big Soul node
  fill(doc, [50, 38, 0]);
  stroke(doc, C.gold);
  doc.setLineWidth(0.6);
  doc.circle(cx, cy, 7, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  rgb(doc, C.goldLight);
  doc.text(String(chart.center), cx, cy + 3.5, { align: 'center' });

  // Labels around outer nodes
  const LABELS = ['MONTH','SKY','YEAR','WEALTH♥','DESTINY','KARMA','DAY','EARTH'];
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(4.5);
  rgb(doc, C.muted);
  outerVals.forEach(({ i }, idx) => {
    const labelPt = pt(i, r + 10);
    doc.text(LABELS[idx], labelPt.x, labelPt.y, { align: 'center' });
  });
};

// ─── MAIN EXPORT ──────────────────────────────────────────────────────────────

export const generateDestinyPDF = async (chart, profile, readings, cosmicData) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });

  const arch = ARCHETYPES[chart.center] || ARCHETYPES[1];
  const dob = (profile?.dateOfBirth || '').split('T')[0];
  const name = profile?.fullName || 'The Seeker';
  const luckyData = getLuckyNumbers(chart);
  const lucky = Array.isArray(luckyData)
    ? luckyData
    : [...new Set([...(luckyData.matrix || []), ...(luckyData.single || [])])];
  const colors = getFavorableColors(chart);
  const careerData = getCareerPaths(chart);
  const careers = Array.isArray(careerData)
    ? careerData
    : [...(careerData?.primary || []), ...(careerData?.secondary || [])];
  const mantra = getMantra(chart);
  const shadow = getShadowWork(chart);
  const relationship = getRelationshipProfile(chart);
  const health = getHealthInsights(chart);
  const moonPhase = cosmicData?.moonPhase;
  const timing = cosmicData?.timing;
  const planets = cosmicData?.planets;

  const TOTAL_PAGES = 5;

  // ══════════════════════════════════════════════════════════════════
  // PAGE 1 — COVER
  // ══════════════════════════════════════════════════════════════════
  pageBg(doc);
  headerBar(doc, 1, TOTAL_PAGES);

  // Hero gradient block
  doc.setFillColor(12, 20, 40);
  rect(doc, 0, 12, W, 75, 0);

  // Gold top accent line
  fill(doc, C.gold);
  rect(doc, 0, 12, W, 0.8, 0);

  // Decorative octagram background (faint, large)
  doc.setGState(doc.GState({ opacity: 0.06 }));
  drawOctagramVector(doc, W/2, 52, 32, chart);
  doc.setGState(doc.GState({ opacity: 1 }));

  // Brand name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  rgb(doc, C.goldLight);
  doc.text('DAIWAYA.LK', W/2, 32, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  rgb(doc, C.muted);
  doc.text('MATRIX OF DESTINY · SRI LANKA', W/2, 38, { align: 'center', charSpace: 1.5 });

  // Gold divider
  stroke(doc, C.gold);
  doc.setLineWidth(0.4);
  line(doc, W/2 - 25, 42, W/2 + 25, 42);

  // Report title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  rgb(doc, C.white);
  doc.text('PERSONAL DESTINY REPORT', W/2, 52, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  rgb(doc, C.silver);
  doc.text('Your Sacred Cosmic Blueprint', W/2, 59, { align: 'center' });

  // Name & date box
  fill(doc, C.surface);
  rect(doc, ML, 72, CW, 20);
  stroke(doc, C.gold);
  doc.setLineWidth(0.3);
  doc.roundedRect(ML, 72, CW, 20, 3, 3, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  rgb(doc, C.white);
  doc.text(name, W/2, 82, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  rgb(doc, C.muted);
  doc.text(`Date of Birth: ${dob}   ·   Soul Center: Node ${chart.center} — ${arch.name}`, W/2, 88, { align: 'center' });

  // Big octagram chart
  drawOctagramVector(doc, W/2, 155, 42, chart);

  // Node label below chart
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  rgb(doc, C.gold);
  doc.text(`SOUL CENTER · NODE ${chart.center}`, W/2, 205, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  rgb(doc, C.silver);
  doc.text(`${arch.name}  ·  ${arch.element}  ·  ${arch.planet}`, W/2, 210, { align: 'center' });

  // Core stats grid (8 nodes)
  const statsY = 218;
  const statsData = [
    { label: 'Soul Center', value: chart.center,                    sub: arch.name,              accent: true },
    { label: 'Life Path',   value: chart.lifePath,                  sub: ARCHETYPES[chart.lifePath]?.name },
    { label: 'Wealth ♥',   value: chart.moneyChannel?.heart,       sub: 'Money Channel Heart' },
    { label: 'Love ♥',     value: chart.relationshipChannel?.heart, sub: 'Relationship Heart' },
    { label: 'Day Node',    value: chart.left,                      sub: 'Physical energy' },
    { label: 'Month Node',  value: chart.top,                       sub: 'Emotional energy' },
    { label: 'Year Node',   value: chart.right,                     sub: 'Ancestral energy' },
    { label: 'Karmic Peak', value: chart.karmicTail?.top,           sub: ARCHETYPES[chart.karmicTail?.top]?.name },
  ];
  const cardW = CW / 4 - 1.5;
  const cardH = 22;
  statsData.forEach(({ label, value, sub, accent }, i) => {
    const col = i % 4, row = Math.floor(i / 4);
    statCard(doc, ML + col * (cardW + 2), statsY + row * (cardH + 2), cardW, cardH, label, value, sub, accent);
  });

  footerBar(doc);

  // ══════════════════════════════════════════════════════════════════
  // PAGE 2 — COSMIC CLIMATE + SOUL & WEALTH READINGS
  // ══════════════════════════════════════════════════════════════════
  doc.addPage();
  pageBg(doc);
  headerBar(doc, 2, TOTAL_PAGES);

  let y = 18;

  // ── Cosmic Climate ──
  y = sectionHead(doc, 'CURRENT COSMIC CLIMATE', y, C.accent4);

  if (moonPhase || timing || planets) {
    // Moon phase card
    if (moonPhase) {
      fill(doc, C.surface);
      rect(doc, ML, y, CW, 18);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      rgb(doc, C.white);
      doc.text(`${moonPhase.symbol}  ${moonPhase.phase}`, ML + 4, y + 6);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      rgb(doc, C.muted);
      doc.text(`${moonPhase.energy} energy  ·  ${moonPhase.illumination}% illuminated`, ML + 4, y + 11);
      rgb(doc, C.silver);
      const advLines = wrapText(doc, moonPhase.advice, CW - 8);
      advLines.slice(0,2).forEach((l, i) => doc.text(l, ML + 4, y + 15 + i * 3.5));
      y += 22;
    }

    // Timing grid
    if (timing) {
      const timingItems = [
        { label: 'Personal Year', value: timing.personalYear, sub: timing.yearTheme },
        { label: 'Personal Month', value: timing.personalMonth, sub: timing.monthTheme },
        { label: 'Universal Year', value: timing.universalYear, sub: '2026' },
      ];
      const tw = CW / 3 - 1.5;
      timingItems.forEach(({ label, value, sub }, i) => {
        statCard(doc, ML + i * (tw + 2), y, tw, 20, label, value, sub, i === 0);
      });
      y += 25;
    }

    // Planets row
    if (planets) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7);
      rgb(doc, C.muted);
      doc.text('PLANETARY POSITIONS TODAY', ML, y);
      y += 4;
      const pArr = Object.values(planets);
      const pw = CW / 4 - 1.5;
      pArr.forEach((p, i) => {
        const col = i % 4, row = Math.floor(i / 4);
        fill(doc, C.surface);
        rect(doc, ML + col * (pw + 2), y + row * 12, pw, 10);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(6);
        rgb(doc, C.muted);
        doc.text(`${p.symbol} ${p.name}`, ML + col*(pw+2) + 2, y + row*12 + 4);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(7);
        rgb(doc, C.white);
        doc.text(`${p.sign} ${p.degree}°`, ML + col*(pw+2) + 2, y + row*12 + 8.5);
      });
      y += Math.ceil(pArr.length / 4) * 12 + 6;
    }
  }

  y += 4;

  // ── Soul Essence Reading ──
  y = sectionHead(doc, 'SOUL ESSENCE', y, C.gold);
  y = readingBlock(doc, `Node ${chart.center} · ${arch.name}`, readings?.soul, y, C.gold, H - 20);

  // ── Wealth Reading (if space) ──
  if (y < H - 50) {
    y = sectionHead(doc, 'WEALTH & CAREER', y + 2, C.accent1);
    y = readingBlock(doc, `Money Channel · Node ${chart.moneyChannel?.heart}`, readings?.wealth, y, C.accent1, H - 20);
  }

  footerBar(doc);

  // ══════════════════════════════════════════════════════════════════
  // PAGE 3 — LOVE, KARMIC & PURPOSE READINGS
  // ══════════════════════════════════════════════════════════════════
  doc.addPage();
  pageBg(doc);
  headerBar(doc, 3, TOTAL_PAGES);

  y = 18;

  // Wealth (overflow)
  if (readings?.wealth) {
    y = sectionHead(doc, 'WEALTH & CAREER (continued)', y, C.accent1);
    y = readingBlock(doc, '', readings?.wealth, y, C.accent1, 100);
    y += 4;
  }

  y = sectionHead(doc, 'LOVE & RELATIONSHIPS', y, C.accent2);
  y = readingBlock(doc, `Heart Channel · Node ${chart.relationshipChannel?.heart}`, readings?.love, y, C.accent2, 160);

  y += 4;
  y = sectionHead(doc, 'KARMIC LEGACY', y, C.accent3);
  y = readingBlock(doc, `Karmic Peak · Node ${chart.karmicTail?.top}`, readings?.karmic, y, C.accent3, H - 20);

  footerBar(doc);

  // ══════════════════════════════════════════════════════════════════
  // PAGE 4 — PURPOSE, FORECAST & NUMEROLOGY DATA
  // ══════════════════════════════════════════════════════════════════
  doc.addPage();
  pageBg(doc);
  headerBar(doc, 4, TOTAL_PAGES);

  y = 18;

  y = sectionHead(doc, 'SPIRITUAL PURPOSE', y, C.accent4);
  y = readingBlock(doc, `Purpose Node ${chart.purpose?.spiritual}`, readings?.purpose, y, C.accent4, 120);

  y += 4;
  y = sectionHead(doc, 'COSMIC FORECAST · 2025–2026', y, C.accent5);
  y = readingBlock(doc, '', readings?.forecast, y, C.accent5, H - 20);

  footerBar(doc);

  // ══════════════════════════════════════════════════════════════════
  // PAGE 5 — DETAILED NUMEROLOGY PROFILE
  // ══════════════════════════════════════════════════════════════════
  doc.addPage();
  pageBg(doc);
  headerBar(doc, 5, TOTAL_PAGES);

  y = 18;
  y = sectionHead(doc, 'DETAILED NUMEROLOGY PROFILE', y, C.gold);

  // Archetype properties
  const propGrid = [
    { label: 'Soul Archetype', value: `Node ${chart.center} — ${arch.name}` },
    { label: 'Element',        value: arch.element },
    { label: 'Ruling Planet',  value: arch.planet },
    { label: 'Sacred Gem',     value: arch.gem },
    { label: 'Power Day',      value: arch.day },
    { label: 'Life Path',      value: `Node ${chart.lifePath} — ${ARCHETYPES[chart.lifePath]?.name || ''}` },
    { label: 'Expression',     value: `Node ${chart.expressionNumber}` },
    { label: 'Soul Urge',      value: `Node ${chart.soulNumber}` },
    { label: 'Personality',    value: `Node ${chart.personalityNumber}` },
    { label: 'Money Entrance', value: `Node ${chart.moneyChannel?.entrance}` },
    { label: 'Money Heart',    value: `Node ${chart.moneyChannel?.heart}` },
    { label: 'Love Entrance',  value: `Node ${chart.relationshipChannel?.entrance}` },
    { label: 'Love Heart',     value: `Node ${chart.relationshipChannel?.heart}` },
    { label: 'Karmic Base',    value: `Node ${chart.karmicTail?.base}` },
    { label: 'Karmic Middle',  value: `Node ${chart.karmicTail?.middle}` },
    { label: 'Karmic Peak',    value: `Node ${chart.karmicTail?.top}` },
    { label: 'Personal Purpose', value: `Node ${chart.purpose?.personal}` },
    { label: 'Social Purpose',   value: `Node ${chart.purpose?.social}` },
    { label: 'Spiritual Purpose',value: `Node ${chart.purpose?.spiritual}` },
    { label: 'Sky Node',         value: `Node ${chart.skyNode}` },
    { label: 'Earth Node',       value: `Node ${chart.earthNode}` },
  ];

  const colW = (CW - 4) / 2;
  propGrid.forEach(({ label, value }, i) => {
    const col = i % 2, row = Math.floor(i / 2);
    const rx = ML + col * (colW + 4);
    const ry = y + row * 7;
    fill(doc, i % 4 < 2 ? C.surface : C.bg);
    doc.rect(rx, ry - 1, colW, 6.5, 'F');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.5);
    rgb(doc, C.muted);
    doc.text(label, rx + 2, ry + 3.5);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(6.5);
    rgb(doc, C.white);
    doc.text(value, rx + colW - 2, ry + 3.5, { align: 'right' });
  });

  y += Math.ceil(propGrid.length / 2) * 7 + 6;

  // ── Lucky Numbers ──
  y = sectionHead(doc, 'LUCKY NUMBERS', y, C.gold);
  lucky.slice(0, 9).forEach((n, i) => {
    nodeBadge(doc, n, ML + 6 + i * 14, y + 4, 5);
  });
  y += 16;

  // ── Favorable Colors ──
  y = sectionHead(doc, 'FAVORABLE COLORS', y, C.gold);
  colors.forEach((c, i) => {
    fill(doc, C.surface);
    rect(doc, ML + i * 28, y, 25, 8);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.5);
    rgb(doc, C.white);
    doc.text(c, ML + i * 28 + 12.5, y + 5, { align: 'center' });
  });
  y += 14;

  // ── Career Paths ──
  y = sectionHead(doc, 'IDEAL CAREER PATHS', y, C.accent1);
  careers.slice(0, 8).forEach((c, i) => {
    const col = i % 4, row = Math.floor(i / 4);
    fill(doc, C.surface);
    rect(doc, ML + col * (CW/4 + 1), y + row * 9, CW/4 - 1, 7);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.5);
    rgb(doc, C.silver);
    doc.text(c, ML + col*(CW/4+1) + (CW/4-1)/2, y + row*9 + 4.5, { align: 'center' });
  });
  y += Math.ceil(careers.length / 4) * 9 + 4;

  // ── Mantra ──
  if (y < H - 30) {
    y = sectionHead(doc, 'POWER MANTRA', y, C.accent3);
    fill(doc, [20, 15, 35]);
    rect(doc, ML, y, CW, 14);
    stroke(doc, C.accent3);
    doc.setLineWidth(0.3);
    doc.roundedRect(ML, y, CW, 14, 3, 3, 'S');
    doc.setFont('helvetica', 'bolditalic');
    doc.setFontSize(9);
    rgb(doc, C.goldLight);
    doc.text(`"${mantra}"`, W/2, y + 9, { align: 'center' });
    y += 20;
  }

  // ── Shadow Work ──
  if (y < H - 30 && shadow?.lesson) {
    y = sectionHead(doc, 'SHADOW WORK', y, C.accent3);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    rgb(doc, C.silver);
    const shadowLines = wrapText(doc, `Lesson: ${shadow.lesson}`, CW);
    shadowLines.forEach((l, i) => doc.text(l, ML, y + i * 4.5));
    y += shadowLines.length * 4.5 + 3;
    if (shadow.gift) {
      rgb(doc, C.accent1);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.5);
      doc.text('Gift:', ML, y);
      doc.setFont('helvetica', 'normal');
      rgb(doc, C.silver);
      const giftLines = wrapText(doc, shadow.gift, CW - 10);
      giftLines.forEach((l, i) => doc.text(l, ML + 10, y + i * 4.5));
      y += giftLines.length * 4.5 + 3;
    }
  }

  footerBar(doc);

  // ── Save ──
  const safeName = name.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  const fileName = `daiwaya_destiny_report_${safeName}_${dob}.pdf`;

  const browserSave = (blob) => {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  if (typeof window !== 'undefined' && typeof document !== 'undefined') {
    try {
      const blob = doc.output('blob');
      browserSave(blob);
    } catch (primaryError) {
      try {
        const arrayBuffer = doc.output('arraybuffer');
        browserSave(new Blob([arrayBuffer], { type: 'application/pdf' }));
      } catch (fallbackError) {
        doc.save(fileName);
      }
    }
  } else {
    doc.save(fileName);
  }
};