import mongoose from 'mongoose';
import Archetype from '../models/Archetype.js';
import dotenv from 'dotenv';

dotenv.config();

const archetypesData = [
  {
    number: 1,
    titleEn: 'The Magician',
    titleSi: 'මැජිෂන්',
    descriptionEn: 'A path of manifestation, leadership, and raw creative power. The Magician represents your ability to turn thoughts into reality through focused will and intention.',
    descriptionSi: 'ප්‍රකාශනය, නායකත්වය සහ අකෙළු නිර්මාණ ශක්තির පথ. මැජිෂන් ඔබේ අවධානය යුක්ත කිරීමෙන් සහ අභිপ්‍රාය මගින් චින්තනයන් සත්‍යතාවට පරිණත කරන ඔබේ ඉටුපත්‍ර නියෝජනය කරයි.',
    career: 'Natural born leader. Pursue entrepreneurial ventures or leadership roles.',
    love: 'Independent spirit, seeks partner who respects autonomy.',
    health: 'Active lifestyle needed. Be mindful of overexertion.',
    spirituality: 'Master of manifestation and intentional creation.',
    finance: 'Strong ability to create wealth through decisive action.',
    keywords: ['leadership', 'manifestation', 'power', 'will'],
    element: 'Fire',
    planet: 'Mercury',
    color: 'Gold'
  },
  {
    number: 2,
    titleEn: 'The High Priestess',
    titleSi: 'ඉහළ පූජිතා',
    descriptionEn: 'A path of intuition, wisdom, and hidden knowledge. The High Priestess calls you to trust your inner voice and access the subconscious realms.',
    descriptionSi: 'අරිස්টිකතා, ඥානය සහ සැඟවුණු දැනුමේ පතුවාසි. ඉහළ පූජිතා ඔබේ අභ්‍යන්තර කණ්ඩුව විශ්වාස කරන ලෙස සහ සිතුවිලි දිලිපිටිවලට ප්‍රවේශ වීමට ඔබට ඉරණම් කරයි.',
    career: 'Excellent mediator and diplomat. Thrive in partnerships and collaborative roles.',
    love: 'Seeks deep emotional connection and partnership.',
    health: 'Balance physical and emotional well-being. Stress management essential.',
    spirituality: 'Gateway to psychic abilities and spiritual wisdom.',
    finance: 'Patient wealth building through calculated decisions.',
    keywords: ['intuition', 'wisdom', 'mystery', 'duality'],
    element: 'Water',
    planet: 'Moon',
    color: 'Silver'
  },
  {
    number: 3,
    titleEn: 'The Empress',
    titleSi: 'අධිරාජිනිය',
    descriptionEn: 'A path of creativity, abundance, and nurturing energy. The Empress invites you to express your gifts and cultivate fertility in all aspects of life.',
    descriptionSi: 'නිර්මාණශීලතා, බහුතරතාව සහ පෝෂණ ශක්ති කර්මස්ස්ස්ස්ස්ස්ස්ස්ස්ස්',
    career: 'Creative professional with strong communication skills.',
    love: 'Communicative and fun-loving in relationships.',
    health: 'Creative outlets support mental health. Avoid nervous tension.',
    spirituality: 'Channel divine feminine energy and creative expression.',
    finance: 'Abundance flows through creative ventures.',
    keywords: ['creativity', 'abundance', 'fertility', 'nurturing'],
    element: 'Earth',
    planet: 'Venus',
    color: 'Emerald'
  },
  {
    number: 4,
    titleEn: 'The Emperor',
    titleSi: 'අධිරාජ',
    descriptionEn: 'A path of authority, structure, and foundation. The Emperor embodies power, control, and the establishment of stable systems.',
    descriptionSi: 'අතුරු, ව්‍යුහය සහ පදනම් පිටි ගිණුම්. අධිරාජ ශක්තිය, පාලනය සහ ස්ථිර පද්ධතිවල ස්ථාපනය නිරූපණ කරයි.',
    career: 'Structured thinker who excels in organization and planning.',
    love: 'Loyal and committed, values stability in love.',
    health: 'Strong constitution. Regular routine and exercise maintain wellness.',
    spirituality: 'Foundation for spiritual mastery and discipline.',
    finance: 'Master of wealth accumulation through systematic planning.',
    keywords: ['authority', 'structure', 'power', 'control'],
    element: 'Fire',
    planet: 'Aries',
    color: 'Red'
  },
  {
    number: 5,
    titleEn: 'The Hierophant',
    titleSi: 'පුරෝහිතයා',
    descriptionEn: 'A path of tradition, wisdom, and spiritual teaching. The Hierophant represents knowledge passed through generations and sacred traditions.',
    descriptionSi: 'සම්ප්‍රදාය, ඥානය සහ ආධ්‍යාත්මික පිළිබිම. පුරෝහිතයා පරපුරා ගිය දැනුම සහ ශුද්ධ සම්ප්‍රදාය නිරූපණ කරයි.',
    career: 'Adaptable and versatile in various professional environments.',
    love: 'Seeks freedom and adventure in romantic relationships.',
    health: 'Variety in exercise keeps you healthy. Avoid extremes.',
    spirituality: 'Keeper of sacred traditions and spiritual knowledge.',
    finance: 'Ethical approach to wealth through principled action.',
    keywords: ['tradition', 'wisdom', 'teaching', 'ritual'],
    element: 'Earth',
    planet: 'Taurus',
    color: 'Blue'
  },
  {
    number: 6,
    titleEn: 'The Lovers',
    titleSi: 'ප්‍රේමිකයෝ',
    descriptionEn: 'A path of love, harmony, and choice. The Lovers represents deep connection, unity, and the power of love to transform.',
    descriptionSi: 'ප්‍රේම, සමගිය සහ තේරීමේ ගමනපත. ප්‍රේමිකයෝ ගැඹුරු සම්බන්ධතා, එකතාවය සහ පරිවර්තනය කිරීමට ප්‍රේමේ ශක්තිය නිරූපණ කරයි.',
    career: 'Caring professional, suited for roles involving service and responsibility.',
    love: 'Caring and responsible partner, creates harmonious home.',
    health: 'Responsible health habits. Balance care for self and others.',
    spirituality: 'Union of divine masculine and feminine aspects.',
    finance: 'Shared prosperity through cooperation and fairness.',
    keywords: ['love', 'harmony', 'union', 'choice'],
    element: 'Air',
    planet: 'Gemini',
    color: 'Yellow'
  },
  {
    number: 7,
    titleEn: 'The Chariot',
    titleSi: 'දිය දුවමිනිය',
    descriptionEn: 'A path of willpower, victory, and self-control. The Chariot represents your ability to harness opposing forces and move forward with determination.',
    descriptionSi: 'ඉතිරි ශක්තිය, විජයතා සහ ස්වයං පාලනයේ ගමනපත. දිය දුවමිනිය ප්‍රතිරෝධী ශක්තිවල අවිය කරන සහ නිර්ණයයෙන් ඉදිරියට ගිරීමේ ඔබේ හැකියාවි නිරූපණ කරයි.',
    career: 'Analytical and spiritual, excels in research, philosophy, or spiritual counseling.',
    love: 'Seeks deep spiritual and intellectual connection.',
    health: 'Spiritual practices support healing. Meditation beneficial.',
    spirituality: 'Chariot of the soul traveling toward enlightenment.',
    finance: 'Dynamic prosperity through focused intention.',
    keywords: ['willpower', 'victory', 'control', 'determination'],
    element: 'Water',
    planet: 'Cancer',
    color: 'Orange'
  },
  {
    number: 8,
    titleEn: 'Strength',
    titleSi: 'බල',
    descriptionEn: 'A path of inner strength, courage, and resilience. Strength represents the gentle power that comes from self-mastery and compassion.',
    descriptionSi: 'අභ්‍යන්තර ශක්තිය, ධෛර්ය සහ ස්ස්ස්ස්ස්ස්ස්ස්ස්ස්ස්',
    career: 'Business acumen and ability to accumulate wealth and power.',
    love: 'Ambitious partner who values respect and equality.',
    health: 'Manage stress through power practices like martial arts.',
    spirituality: 'Mastery of ego and animal instincts through love.',
    finance: 'Material power through inner discipline and focus.',
    keywords: ['strength', 'courage', 'resilience', 'mastery'],
    element: 'Fire',
    planet: 'Leo',
    color: 'Purple'
  },
  {
    number: 9,
    titleEn: 'The Hermit',
    titleSi: 'ගිනුවරා',
    descriptionEn: 'A path of introspection, wisdom, and spiritual seeking. The Hermit represents the inner journey toward enlightenment and truth.',
    descriptionSi: 'ස්වයං විශ්ලේෂණය, ඥානය සහ ආධ්‍යාත්මික සෙවීමේ ගමනපත. ගිනුවරා ඉතිරිකරණ සහ සත්‍යතාවට ඉතිරිකරණ ගමනපතට වරණ කරයි.',
    career: 'Humanitarian values, suited for charitable or social work.',
    love: 'Compassionate and universal in love, values service.',
    health: 'Humanitarian health pursuits. Universal healing energy.',
    spirituality: 'Lantern bearer of spiritual wisdom and enlightenment.',
    finance: 'Wealth through sharing knowledge and service.',
    keywords: ['introspection', 'wisdom', 'seeking', 'truth'],
    element: 'Earth',
    planet: 'Virgo',
    color: 'Indigo'
  },
  {
    number: 10,
    titleEn: 'Wheel of Fortune',
    titleSi: 'ඉසින් පිටිය',
    descriptionEn: 'A path of destiny, cycles, and divine intervention. The Wheel represents the eternal cycles of life and the turning point of fate.',
    descriptionSi: 'ඉසින්, චක්‍ර සහ දෛවීය අවතරණ ගමනපත. ඉසින් පිටිය ජීවිතයේ සදා චක්‍ර සහ ඉසින්ස්ස්ස්ස්',
    career: 'Leader with potential for new ventures and fresh starts.',
    love: 'Potential for powerful new romantic beginnings.',
    health: 'Fresh starts with health regimens. Powerful potential for renewal.',
    spirituality: 'Cosmic timing and divine synchronicity.',
    finance: 'Cycles of wealth and opportunity aligned with destiny.',
    keywords: ['destiny', 'cycles', 'fortune', 'intervention'],
    element: 'Fire',
    planet: 'Jupiter',
    color: 'Gold'
  },
  {
    number: 11,
    titleEn: 'Justice',
    titleSi: 'යුක්තිය',
    descriptionEn: 'A path of balance, karma, and truth. Justice represents the law of cause and effect, karmic balance, and the pursuit of fairness.',
    descriptionSi: 'ශේෂය, කර්ම සහ සත්‍යතාවේ ගමනපත. යුක්තිය හේතු සහ ඵල නිතිය, කර්ම ශේෂය සහ ස්ස්ස්ස්ස්',
    career: 'Visionary with strong intuition, suited for innovation.',
    love: 'Intuitive and spiritual connection with partner.',
    health: 'Intuitive health awareness. Trust your body\'s signals.',
    spirituality: 'Illuminated consciousness and higher awareness.',
    finance: 'Universal prosperity through karmic alignment.',
    keywords: ['balance', 'karma', 'truth', 'justice'],
    element: 'Air',
    planet: 'Libra',
    color: 'Green'
  },
  {
    number: 12,
    titleEn: 'The Hanged Man',
    titleSi: 'එල්ල ගත් මිතුරු',
    descriptionEn: 'A path of sacrifice, surrender, and spiritual transformation. The Hanged Man represents the necessary pause for perspective and enlightenment.',
    descriptionSi: 'පුජනය, සඳහා සහ ආධ්‍යාත්මික පරිවර්තනයේ ගමනපත. එල්ල ගත් මිතුරු දසෂ්ටිකෝණ සඳහා සහ ඉතිරිකරණ සඳහා ඕනෑම විරාමයි නිරූපණ කරයි.',
    career: 'Transformative role, excellent for healing and counseling professions.',
    love: 'Transformative love that heals and renews.',
    health: 'Healing through transformation and sacrifice.',
    spirituality: 'Initiation and spiritual death-rebirth cycles.',
    finance: 'Letting go of material attachments for higher good.',
    keywords: ['sacrifice', 'surrender', 'transformation', 'pause'],
    element: 'Water',
    planet: 'Neptune',
    color: 'Turquoise'
  },
  {
    number: 13,
    titleEn: 'Death',
    titleSi: 'මරණය',
    descriptionEn: 'A path of transformation, endings, and new beginnings. Death represents the necessary dissolution of old patterns to birth the new.',
    descriptionSi: 'පරිවර්තනයේ, අවසාන සහ නව ආරම්භ ගමනපත. මරණය නුතන කිරීමට පැරණි ඉරණම ගිණුම් විසර්ජනයි නිරූපණ කරයි.',
    career: 'Pioneer in transformation and spiritual growth fields.',
    love: 'Evolving relationship that promotes spiritual growth.',
    health: 'Spiritual evolution supports healing journey.',
    spirituality: 'Death of ego, rebirth of soul consciousness.',
    finance: 'Complete financial transformation and renewal.',
    keywords: ['transformation', 'endings', 'renewal', 'rebirth'],
    element: 'Water',
    planet: 'Scorpio',
    color: 'Black'
  },
  {
    number: 14,
    titleEn: 'Temperance',
    titleSi: 'සම',
    descriptionEn: 'A path of balance, moderation, and healing. Temperance represents the integration of opposites and the healing of fragmentation.',
    descriptionSi: 'ශේෂයේ, සම සහ සුවෝපනයේ ගමනපත. සම ඔරුවක සහ පුංඡක ශුද්ධතා ගිණුම් සඳහා සහ පුංඡකතා සුවෝපනයි නිරූපණ කරයි.',
    career: 'Balanced approach to work, suited for diplomacy and negotiation.',
    love: 'Balanced and harmonious romantic partnership.',
    health: 'Balance in diet and exercise for optimal health.',
    spirituality: 'Alchemy of integrating all aspects of self.',
    finance: 'Steady wealth accumulation through moderation.',
    keywords: ['balance', 'moderation', 'healing', 'integration'],
    element: 'Fire',
    planet: 'Sagittarius',
    color: 'Violet'
  },
  {
    number: 15,
    titleEn: 'The Devil',
    titleSi: 'දුෂ්ටයා',
    descriptionEn: 'A path of challenge, evolution, and liberation. The Devil represents the chains we create through fear and the power of freedom.',
    descriptionSi: 'අභිරුචිතා, ඉතිරිකරණ සහ නිදහසේ ගමනපත. දුෂ්ටයා අපි බයෙන් නිර්මාණ කරන දැඩි සහ නිදහසේ ශක්තිය නිරූපණ කරයි.',
    career: 'Challenge-lover who thrives in dynamic and evolving environments.',
    love: 'Passionate and intense emotional connection.',
    health: 'Challenge yourself with health goals. Intensity aids growth.',
    spirituality: 'Shadow work and integration of darker aspects.',
    finance: 'Power through understanding material magnetism.',
    keywords: ['challenge', 'evolution', 'liberation', 'power'],
    element: 'Earth',
    planet: 'Capricorn',
    color: 'Red'
  },
  {
    number: 16,
    titleEn: 'The Tower',
    titleSi: 'කුලුණ',
    descriptionEn: 'A path of sudden change, revelation, and awakening. The Tower represents the necessary breakdown that precedes breakthrough.',
    descriptionSi: 'හදිසි සුවිධාතා, අනාවරණය සහ අවබෝධනයේ ගමනපත. කුලුණ අභිරුචිතාවට පෙර සාධකයි දිසුණු බිඳුම නිරූපණ කරයි.',
    career: 'Transformative impact in career, naturally breaks outdated systems.',
    love: 'Transformative meeting that changes life direction.',
    health: 'Sudden health revelations lead to powerful change.',
    spirituality: 'Lightning bolt of truth and divine revelation.',
    finance: 'Complete financial restructuring and rebirth.',
    keywords: ['sudden', 'revelation', 'awakening', 'breakthrough'],
    element: 'Fire',
    planet: 'Mars',
    color: 'Red'
  },
  {
    number: 17,
    titleEn: 'The Star',
    titleSi: 'තරුණ',
    descriptionEn: 'A path of hope, inspiration, and guidance. The Star represents divine guidance, clarity of purpose, and the light within darkness.',
    descriptionSi: 'ආශා, අනුප්‍රේරණ සහ නිබන්ධනයේ ගමනපත. තරුණ දෛවීය නිබන්ධනය, අරමුණු පැහැදිලිතාවය සහ අඳුරින් ඉතිරි නිරූපණ කරයි.',
    career: 'Inspirational guide, excellent mentor and beacon of hope.',
    love: 'Inspiring and hopeful love that guides.',
    health: 'Inspired wellness journey with hopeful outcomes.',
    spirituality: 'Connection to divine source and cosmic consciousness.',
    finance: 'Abundance flows from hope and positive vision.',
    keywords: ['hope', 'inspiration', 'guidance', 'clarity'],
    element: 'Air',
    planet: 'Aquarius',
    color: 'Blue'
  },
  {
    number: 18,
    titleEn: 'The Moon',
    titleSi: 'චන්ද්‍රයා',
    descriptionEn: 'A path of illusion, intuition, and dreams. The Moon represents the subconscious, intuition, and the mysterious realms of emotion.',
    descriptionSi: 'අසත්‍ය, අරිස්ටිකතා සහ සිහින ගමනපත. චන්ද්‍රයා සිතුවිලි, අරිස්ටිකතා සහ චිතුවිලි සිතුවිලි නිරූපණ කරයි.',
    career: 'Intuitive professional, suited for roles involving mystery or imagination.',
    love: 'Mysterious and intuitive romantic connection.',
    health: 'Trust intuition for mysterious health insights.',
    spirituality: 'Psychic sensitivity and subconscious exploration.',
    finance: 'Wealth through understanding hidden patterns.',
    keywords: ['illusion', 'intuition', 'dreams', 'mystery'],
    element: 'Water',
    planet: 'Pisces',
    color: 'Silver'
  },
  {
    number: 19,
    titleEn: 'The Sun',
    titleSi: 'සූර්ය',
    descriptionEn: 'A path of success, clarity, and joy. The Sun represents enlightenment, vitality, and the triumph of consciousness over all obstacles.',
    descriptionSi: 'සාර්ථකතා, පැහැදිලිතාවය සහ ප්‍රීතිය ගමනපත. සූර්ය ඉතිරිකරණය, ජීවිතීය සහ සියලු බාධක ඉතිරි ජයගැනීම නිරූපණ කරයි.',
    career: 'Achiever with clarity of vision, natural success.',
    love: 'Clear and successful romantic partnership.',
    health: 'Clear health goals achieve success.',
    spirituality: 'Illuminated consciousness and divine union.',
    finance: 'Abundant success and material fulfillment.',
    keywords: ['success', 'clarity', 'joy', 'enlightenment'],
    element: 'Fire',
    planet: 'Sun',
    color: 'Gold'
  },
  {
    number: 20,
    titleEn: 'Judgment',
    titleSi: 'විනිශ්චය',
    descriptionEn: 'A path of awakening, calling, and resurrection. Judgment represents the call to higher purpose and spiritual awakening.',
    descriptionSi: 'ඉතිරිකරණය, ඉරණම සහ ප්‍රතිස්ස්ස්ස්ස්ස්ස්ස්ස්ස්ස්ස්',
    career: 'Awakened professional with renewal energy, excellent for training and development.',
    love: 'Awakening love that brings renewal and judgment.',
    health: 'Awakening to true wellness potential.',
    spirituality: 'Spiritual resurrection and higher calling.',
    finance: 'Renewal of financial purpose and abundance.',
    keywords: ['awakening', 'calling', 'resurrection', 'renewal'],
    element: 'Fire',
    planet: 'Pluto',
    color: 'Gold'
  },
  {
    number: 21,
    titleEn: 'The World',
    titleSi: 'ලෝකය',
    descriptionEn: 'A path of completion, wholeness, and integration. The World represents the fulfillment of a cycle and the beginning of a new journey.',
    descriptionSi: 'සම්පූර්ණතා, සමස්තතා සහ ගිණුම් ගිණුම් ගმනපත. ලෝකය චක්‍ර සම්පූර්ණතා සහ නුතන ගමනපතේ ආරම්භයි නිරූපණ කරයි.',
    career: 'Completes projects successfully, master of integration.',
    love: 'Complete and fulfilled romantic integration.',
    health: 'Complete health integration and fulfillment.',
    spirituality: 'Completion of soul journey and cosmic consciousness.',
    finance: 'Total wealth integration and fulfillment.',
    keywords: ['completion', 'wholeness', 'integration', 'fulfillment'],
    element: 'Earth',
    planet: 'Saturn',
    color: 'Green'
  },
  {
    number: 22,
    titleEn: 'The Master Builder',
    titleSi: 'පරිමාණ තක්සේරුකරු',
    descriptionEn: 'A path of mastery, vision, and legacy. The Master Builder represents the manifestation of the highest potential and the creation of lasting impact.',
    descriptionSi: 'ශිල්පකරණය, දසෂ්ටිකෝණ සහ පරම්පරාවල ගමනපත. පරිමාණ තක්සේරුකරු ඉහළතම විභවතාවේ ප්‍රකාශනයි සහ රැඳිටිම ඇඟවීම සඳහා සාදර්ශනය නිරූපණ කරයි.',
    career: 'Master builder and visionary leader with lasting legacy.',
    love: 'Master relationship with legendary quality.',
    health: 'Master of holistic health and legacy.',
    spirituality: 'Mastery of spiritual evolution and cosmic consciousness.',
    finance: 'Master builder of generational wealth.',
    keywords: ['mastery', 'vision', 'legacy', 'completion'],
    element: 'All',
    planet: 'All',
    color: 'All'
  }
];

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing archetypes
    await Archetype.deleteMany({});

    // Insert new archetypes
    await Archetype.insertMany(archetypesData);
    console.log('✓ Seeded 22 archetypes successfully');

    await mongoose.disconnect();
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  }
};

seedDatabase();
